### ISSUE TITLE
Are you reverse engineering the original or are you recreating it from scratch?

### ISSUE THREAD

**Issue by 1oom-fork** [nextghost/openorion2#5]

**Comment by nextghost** [comment]
This project is a reverse engineering effort to recreate the original game as closely as possible. Original game data files (`*.LBX`) are required. The code is 100% written from scratch, though. We did not disassemble the original binaries and have no plans to ever do so.

**Comment by 1oom-fork** [comment]
Why am I interested? For example, in 1oom the code is recreated from binaries and there are a lot of interesting errors visible that would otherwise be almost impossible to find. So you might be missing something?

**Comment by nextghost** [comment]
I've already found interesting errors in the original game. Start or load a game in MOO2. Create a fleet of 16 or more ships. Open the Leaders screen, switch to the Ship Officers tab and select that fleet. Now click the scroll bar in the upper right corner (the bar itself, not the buttons). The game will crash.
